services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: daler
      POSTGRES_PASSWORD: daler123
      POSTGRES_DB: coworkingdb
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
